---
"$schema": http://json-schema.org/draft-04/hyper-schema
title: Prizey - Product
description: A product is a shopify product
stability: prototype
type:
- object
definitions:
  identifier:
    description: shopify URL handler
    readOnly: true
    type:
    - string
  id:
    description: the product id
    readOnly: true
    type: integer
  title:
    description: the product title
    readOnly: true
    type: string
  image:
    description: the product image
    readOnly: true
    type: string
  price:
    description: the product price
    readOnly: true
    type: string
  identity:
    anyOf:
    - $ref: "/schemata/product#/definitions/id"
links:
- title: List
  description: List of products
  href: "/products/{(%2Fschemata%2Fproduct%23%2Fdefinitions%2Fidentifier)}"
  method: GET
  rel: instances
  schema:
    additionalProperties: false
    properties: {}
    type:
    - object
  targetSchema:
    anyOf:
      - type: array
        items:
          "$ref": "/schemata/product"
      - "$ref": "/schemata/error"
properties:
  id:
    $ref: "/schemata/product#/definitions/id"
  title:
    $ref: "/schemata/product#/definitions/title"
  image:
    $ref: "/schemata/product#/definitions/image"
  price:
    $ref: "/schemata/product#/definitions/price"
id: schemata/product
